"""add field manualUpload

Revision ID: 682ebeef8712
Revises: d77cdd298f36
Create Date: 2022-03-09 11:42:20.830199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '682ebeef8712'
down_revision = 'd77cdd298f36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monopoly', sa.Column('manualUpload', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monopoly', 'manualUpload')
    # ### end Alembic commands ###
