"""initial

Revision ID: d77cdd298f36
Revises: 
Create Date: 2022-03-03 18:06:49.260903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd77cdd298f36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monopoly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=True),
    sa.Column('companyName', sa.String(length=512), nullable=True),
    sa.Column('registry', sa.String(length=512), nullable=True),
    sa.Column('section', sa.String(length=512), nullable=True),
    sa.Column('docNumber', sa.String(length=13), nullable=True),
    sa.Column('region', sa.String(length=512), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('dateFirstReg', sa.Date(), nullable=True),
    sa.Column('lastCheck', sa.DateTime(), nullable=True),
    sa.Column('removeDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__monopoly')),
    sa.UniqueConstraint('inn', name=op.f('uq__monopoly__inn'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monopoly')
    # ### end Alembic commands ###
